/*! Generated by Font Squirrel (https://www.fontsquirrel.com) on November 5, 2018 */
import { injectGlobal } from 'styled-components';
import { avertaRegularData } from './avertaRegularData';
import { avertaBoldData } from './avertaBoldData';

// eslint-disable-next-line no-unused-expressions
injectGlobal`
  @font-face {
    font-family: 'Averta';
    src: url(${avertaRegularData}) format('woff2');
    font-weight: bold;
    font-style: normal;
  }

  @font-face {
    font-family: 'Averta';
    src: url(${avertaBoldData}) format('woff2');
    font-weight: normal;
    font-style: normal;
  }
`;
